//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiredHunters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int apply_no { get; set; }
        public string Full_name { get; set; }
        public string Email_Address { get; set; }
        public string Phonenumber { get; set; }
        public string Con_Message { get; set; }
    }
}
