//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiredHunters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freelencer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Freelencer()
        {
            this.Applylists = new HashSet<Applylist>();
        }
    
        public int f_no { get; set; }
        public string Freelencer_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string F_Address { get; set; }
        public Nullable<System.DateTime> DateofJoining { get; set; }
        public Nullable<int> JobCompleted { get; set; }
        public Nullable<float> NetIncome { get; set; }
        public Nullable<float> rating { get; set; }
        public string username { get; set; }
        public Nullable<int> isEmailVarified { get; set; }
        public string pass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applylist> Applylists { get; set; }
    }
}
