//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiredHunters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Applylists = new HashSet<Applylist>();
        }
    
        public int J_no { get; set; }
        public string Job_ID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Locations { get; set; }
        public Nullable<int> isAvailable { get; set; }
        public Nullable<int> Recruiter_ID { get; set; }
        public string AskingPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applylist> Applylists { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
