//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiredHunters.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HiredHuntersEntities1 : DbContext
    {
        public HiredHuntersEntities1()
            : base("name=HiredHuntersEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applylist> Applylists { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Freelencer> Freelencers { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Manange> Mananges { get; set; }
        public virtual DbSet<Recruiter> Recruiters { get; set; }
    }
}
